Update PYPI_ENDPOINT to use https
Using http seems to cause a ProtocolError

    xmlrpclib.ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>

Changing the endpoint to https:// instead of http:// seems to work. Possibly the PyPI website has been changed to allow https requests only.